# Generated by Django 5.0 on 2023-12-22 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curses', '0012_curs_оплачено_'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('status', models.CharField(max_length=10)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('curs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curses.curs')),
            ],
        ),
    ]
