# Generated by Django 5.0 on 2023-12-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
