# Generated by Django 5.0 on 2023-12-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kurs',
            new_name='Curs',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
