# Generated by Django 5.0 on 2023-12-07 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0002_rename_kurs_curs_alter_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='curs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curs', to='curses.curs', verbose_name='курс'),
        ),
    ]
