# Generated by Django 5.0 on 2023-12-07 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0003_lesson_curs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='curs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curses.curs', verbose_name='курс'),
        ),
    ]
