# Generated by Django 5.0 on 2023-12-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0004_alter_lesson_curs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url_video',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка на видео'),
        ),
    ]
