# Generated by Django 5.0 on 2023-12-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0005_alter_lesson_url_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='curs',
        ),
        migrations.AddField(
            model_name='curs',
            name='lessons',
            field=models.ManyToManyField(to='curses.lesson'),
        ),
    ]
