# Generated by Django 5.0 on 2023-12-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0007_curs_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curs',
            name='lessons',
            field=models.ManyToManyField(blank=True, null=True, to='curses.lesson'),
        ),
    ]
