# Generated by Django 5.0 on 2023-12-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0009_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curs',
            name='lessons',
        ),
        migrations.AddField(
            model_name='curs',
            name='lessons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curses.lesson'),
        ),
    ]
