# Generated by Django 5.0 on 2023-12-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curses', '0011_curs_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='curs',
            name='Оплачено?',
            field=models.BooleanField(default=False),
        ),
    ]
